steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-west1-docker.pkg.dev/teacher-coach-485623/cloud-run-source-deploy/lessonlens-api:v1.1.0'
      - '-t'
      - 'us-west1-docker.pkg.dev/teacher-coach-485623/cloud-run-source-deploy/lessonlens-api:latest'
      - '-f'
      - 'CloudRunBackend/Dockerfile'
      - '.'
images:
  - 'us-west1-docker.pkg.dev/teacher-coach-485623/cloud-run-source-deploy/lessonlens-api:v1.1.0'
  - 'us-west1-docker.pkg.dev/teacher-coach-485623/cloud-run-source-deploy/lessonlens-api:latest'
options:
  logging: CLOUD_LOGGING_ONLY
